config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :customers
  devise_for :planners

  resources :reservable_frames, only: %i[index create destroy]
  resources :planners, only: %i[index] do
    resources :reservations, shallow: true
  end
  get 'mypage' => 'mypage#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < User
  has_many :reservations, dependent: :destroy
end

app/models/planner.rb
# frozen_string_literal: true

class Planner < User
  has_many :reservable_frames, dependent: :destroy
  has_many :reservations, through: :reservable_frames
end

app/models/reservable_frame.rb
# frozen_string_literal: true

class ReservableFrame < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_one :reservation, dependent: :destroy
  belongs_to_active_hash :time_frame
  belongs_to :planner

  validates :planner, presence: true
  validates :time_frame, presence: true
  validates :date, presence: true

  validate :validate_time_frame_is_enable

  scope :reservable, -> { left_joins(:reservation).where(Reservation.arel_table[:id].eq(nil)) }

  private

  def validate_time_frame_is_enable
    return if date.nil?
    return if time_frame.nil?

    errors.add(:time_frame, '有効な時間枠ではありません。') unless time_frame.enable?(date)
  end
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :reservable_frame

  validates :reservable_frame, uniqueness: true
end

app/models/time_frame.rb
# frozen_string_literal: true

class TimeFrame < ActiveHash::Base
  START_TIME_OF_DAY = Tod::TimeOfDay.new(10, 0).freeze #  10:00~
  END_TIME_OF_DAY = Tod::TimeOfDay.new(18, 0).freeze   # ~18:00
  SEC_PER_FRAME = 1800 # 30 minutes
  FRAMES_PER_DAY = Tod::Shift.new(START_TIME_OF_DAY, END_TIME_OF_DAY).duration \
                  / SEC_PER_FRAME.freeze
  SAT_START_TIME_OF_DAY = Tod::TimeOfDay.new(11, 0) #  11:00~
  SAT_END_TIME_OF_DAY = Tod::TimeOfDay.new(15, 0)   # ~15:00

  #
  # START_TIME_OF_DAYからEND_TIME_OF_DAYまでの全枠(FRAMES_PER_DAY毎)をdataとして格納。
  #
  # start: その枠の開始時間
  #   end: その枠の終了時間
  #
  self.data = Array.new(FRAMES_PER_DAY) do |i|
    {
      id: i + 1,
      start: START_TIME_OF_DAY + SEC_PER_FRAME * i,
      end: START_TIME_OF_DAY + SEC_PER_FRAME * (i + 1)
    }
  end

  def self.first_on_saturday
    find_by(start: SAT_START_TIME_OF_DAY)
  end

  def self.last_on_saturday
    find_by(end: SAT_END_TIME_OF_DAY)
  end

  def enable?(date)
    if date.nil?
      false
    elsif date.saturday?
      start_idx = TimeFrame.first_on_saturday.id
      end_idx = TimeFrame.last_on_saturday.id
      (start_idx..end_idx).cover?(id)
    elsif date.sunday?
      false
    else
      true
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :type, length: { maximum: 30 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/date_concern.rb
# frozen_string_literal: true

module DateConcern
  private

  def weekly_dates
    Time.zone.today.upto(Time.zone.today + 6.days)
  end
end

app/controllers/mypage_controller.rb
# frozen_string_literal: true

class MypageController < ApplicationController
  include DateConcern

  before_action :authenticate_account!
  before_action :set_dates, only: %i[index]
  before_action :set_planner_reservations, only: %i[index], if: :planner_signed_in?
  before_action :set_customer_reservations, only: %i[index], if: :customer_signed_in?

  def index; end

  private

  def authenticate_account!
    redirect_to root_path unless customer_signed_in? || planner_signed_in?
  end

  def set_dates
    @dates = weekly_dates
  end

  def set_planner_reservations
    @planner_reservations =
      current_planner
      .reservations
      .eager_load(:customer)
      .where(reservable_frames: { date: @dates.to_a })
      .order(ReservableFrame.arel_table[:date],
             ReservableFrame.arel_table[:time_frame_id])
  end

  def set_customer_reservations
    @customer_reservations =
      current_customer
      .reservations
      .eager_load(reservable_frame: :planner)
      .where(reservable_frames: { date: @dates.to_a })
      .order(ReservableFrame.arel_table[:date],
             ReservableFrame.arel_table[:time_frame_id])
  end
end

app/controllers/planners_controller.rb
# frozen_string_literal: true

class PlannersController < ApplicationController
  def index
    @planners = Planner.all
  end
end

app/controllers/reservable_frames_controller.rb
# frozen_string_literal: true

class ReservableFramesController < ApplicationController
  include DateConcern

  def index
    @dates = weekly_dates
    @reservable_frames = current_planner.reservable_frames.where(date: @dates.to_a)
    @time_frames = TimeFrame.all
  end

  def create
    @reservable_frame = current_planner.reservable_frames.build(reservable_frame_params)
    if @reservable_frame.save
      render json: @reservable_frame
    else
      render json: @reservable_frame.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @reserved_frame = current_planner.reservable_frames.find(params[:id])
    @reserved_frame.destroy
  end

  private

  def reservable_frame_params
    params.require(:reservable_frame).permit(:time_frame_id, :date)
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  def index
    @planner = Planner.find(params[:planner_id])
    @time_frames = TimeFrame.all
    @dates = Time.zone.today.upto(Time.zone.today + 6.days)
    @reservable_frames = @planner.reservable_frames.reservable
  end

  def create
    @reservation = current_customer.reservations.build(reservation_params)
    if @reservation.save
      render json: @reservation
    else
      render json: @reservation.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:reservable_frame_id)
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/mypage_helper.rb
# frozen_string_literal: true

module MypageHelper
end

app/helpers/planners_helper.rb
# frozen_string_literal: true

module PlannersHelper
end

app/helpers/reservable_frames_helper.rb
# frozen_string_literal: true

module ReservableFramesHelper
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FpSys
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'partials/header'
    = yield

app/views/layouts/top.html.slim
doctype html
html
  head
    title
      | ファイナンシャル相談所
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/mypage/_customer_reservations.html.slim
h2.u-h2
  | 予約の確認(利用者向け)
table.p-mypage-table
  thead
    tr
      th 日付
      th 時間
      th プランナー
  tbody
    - customer_reservations.each do |r|
      tr
        td = r.reservable_frame.date
        td
          = r.reservable_frame.time_frame.start.strftime('%H:%M')
          | 〜
          = r.reservable_frame.time_frame.end.strftime('%H:%M')
        td = r.reservable_frame.planner.name

app/views/mypage/_planner_reservations.html.slim
h2.u-h2
  | 予約者一覧(プランナー向け)
table.p-mypage-table
  thead
    tr
      th 日付
      th 時間
      th 予約者
  tbody
    - planner_reservations.each do |r|
      tr
        td = r.reservable_frame.date
        td
          = r.reservable_frame.time_frame.start.strftime('%H:%M')
          | 〜
          = r.reservable_frame.time_frame.end.strftime('%H:%M')
        td = r.customer.name

app/views/mypage/index.html.slim
.l-container
  .p-mypage
    - if planner_signed_in?
      = render 'planner_reservations', planner_reservations: @planner_reservations
    - if customer_signed_in?
      = render 'customer_reservations', customer_reservations: @customer_reservations

app/views/partials/_header.html.slim
.l-header
  h1.l-header__title
    = link_to 'ファイナンシャル相談所', root_path
  .l-header__buttons
    - if customer_signed_in?
      = link_to 'マイページ', mypage_path, class: 'l-header__buttons__btn'
      = link_to 'ログアウト', destroy_customer_session_path, method: 'delete', class: 'l-header__buttons__btn'
    - elsif planner_signed_in?
      = link_to 'マイページ', mypage_path, class: 'l-header__buttons__btn'
      = link_to 'ログアウト', destroy_planner_session_path, method: 'delete', class: 'l-header__buttons__btn'

app/views/planners/index.html.slim
.l-container
  .p-planners
    h1.u-h1
      | 相談したいプランナーを選んでください。

    ul
      - @planners.each do |planner|
        li = link_to planner.name, planner_reservations_path(planner)

app/views/reservable_frames/index.html.slim
.l-container
  .p-reservable-frames
    h1.u-h1 予約枠受付設定画面
    small 予約を受け付ける枠を設定することができます。

    table.js-reservable-frame-table[data-reservable-frames=@reservable_frames.to_json]
      thead
        tr
          th
          - @time_frames.each do |frame|
            th
              = frame.start.strftime('%H:%M')
              | ~
      tbody
        - @dates.each do |date|
          tr
            td = date
            - @time_frames.each do |frame|
              td.js-time-frame-td[data={ date: date, frame_id: frame.id, enable: frame.enable?(date).to_s, reservable: 'false' }]

app/views/reservations/index.html.slim
.l-container
  .p-reservations
    h1.u-h1
      = "#{@planner.name}さんに予約"
    table.p-reservations-table.js-reservations-table[data={ reservable_frames: @reservable_frames.to_json }]
      thead
        tr
          th
          - @time_frames.each do |tf|
            th = tf.start.strftime('%H:%M')
      tbody
        - @dates.each do |date|
          tr
            th = date.strftime('%m/%d')
            - @time_frames.each do |frame|
              td.js-time-frame-td[data={ time_frame_id: frame.id, date: date.to_s }]

app/views/top/index.html.slim
.p-hero
  .p-hero__buttons
    - if customer_signed_in? || planner_signed_in?
      = link_to 'マイページ', mypage_path, class: 'p-hero__buttons__btn'
    - if customer_signed_in?
      = link_to 'ログアウト', destroy_customer_session_path, method: 'delete', class: 'p-hero__buttons__btn'
    - elsif planner_signed_in?
      = link_to 'ログアウト', destroy_planner_session_path, method: 'delete', class: 'p-hero__buttons__btn'
  h1.p-hero__title
    | ファイナンシャル相談所
.p-offer
  .p-offer-content--customer
    h2 相談したい方
    - if customer_signed_in?
      = link_to '予約する', planners_path, class: 'p-offer-content__btn'
    - else
      = link_to '登録する', new_customer_registration_path, class: 'p-offer-content__btn'
      = link_to 'ログインする', new_customer_session_path, class: 'p-offer-content__btn'
  .p-offer-content--planner
    h2 FPの方
    - if planner_signed_in?
      = link_to '予約枠設定', reservable_frames_path, class: 'p-offer-content__btn'
    - else
      = link_to '登録する', new_planner_registration_path, class: 'p-offer-content__btn'
      = link_to 'ログインする', new_planner_session_path, class: 'p-offer-content__btn'